# Generated by Django 3.2.6 on 2021-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211006_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_expires',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='ShopUserProfile',
        ),
    ]
